### ISSUE TITLE
No CSS snapshotted

### ISSUE THREAD

**Issue by robinweser** [Kilix/jest-fela-react#1]
Is this package supposed to already work fine?
I've tried to use it locally and set up just as the README points, but I don't get anything added to my snapshots.

I am trying with fela@5.x.x (without fela-monolithic)

**Comment by AugustinLF** [comment]
Hmmm, I'll have a look next week (currently on holidays), but it works with monolithic (that's how we use it, and that's the [tests](https://github.com/Kilix/jest-fela-react/blob/master/src/__tests__/__snapshots__/serializer.js.snap) I wrote), but it should work. I guess you properly used the `expect.addSnapshotSerializer`? I'll come back to you as soon as I tried to reproduce :)

**Comment by wcastand** [comment]
I tried to create a simple [repo](https://github.com/wcastand/test-jest-fela-react)

It seems to work for me.

```javascript

import React from "react";
import createSerializer from "jest-fela-react";
import { createRenderer } from "fela";
import { Provider, createComponent } from "react-fela";
import monolithic from "fela-monolithic";
import renderer from "react-test-renderer";

const felaRenderer = createRenderer();

expect.addSnapshotSerializer(createSerializer(felaRenderer));

test("test 1", () => {
  const Test = createComponent(() => ({ fontSize: "16px", color: "red" }));
  const tree = renderer
    .create(
      <Provider renderer={felaRenderer}>
        <Test>Test</Test>
      </Provider>
    )
    .toJSON();
  expect(tree).toMatchSnapshot();
});

```

If i change the Component `Test`, the snapshot is updated with the css rendered like the example.
I tried with and without monolithic.

**Comment by AugustinLF** [comment]
Hey, I added a [test case](https://github.com/Kilix/jest-fela-react/blob/master/src/__tests__/serializerWithoutMonolithic.js) to cover the case without using `monolithic`, and the snapshot looks as [expected](https://github.com/Kilix/jest-fela-react/blob/master/src/__tests__/__snapshots__/serializerWithoutMonolithic.js.snap).

Could you share how you set it up, so we could see where is the problem?

**Comment by AugustinLF** [comment]
@rofrischmann hey, did you have the time to look at this problem? Is this still a thing?

**Comment by robinweser** [comment]
Heyhey, oh I am sorry for not responding actually.
I figured out that the problem was something else, and that I actually works as expected^^

Still thank you for trying out!
